name: profiling
on:
  push:
    paths-ignore:
      - pyproject.toml
    branches:
      - '**'
    tags:
      - '**'

  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  profiling:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: pip install -e ".[dev]"

      - name: Run profiler
        run: python profiling/profile.py

      - name: Push results to profiling branch
        run: |
          set -euo pipefail

          PROFILING_BRANCH=profiling
          SHA_COMMIT=$(git rev-parse --short HEAD)
          RESULTS_DIR="$(date +"%Y_%m_%d")_commit_$SHA_COMMIT"

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # Checkout profiling branch or create it.
          if git ls-remote --exit-code --heads origin "$PROFILING_BRANCH" >/dev/null; then
            git fetch origin "$PROFILING_BRANCH"
            git switch "$PROFILING_BRANCH"
          else
            git checkout --orphan "$PROFILING_BRANCH"
            git reset --hard
            echo "perf data" >> README.md
            git add README.md
            git commit -m "Initial commit"
            git push -u origin "$PROFILING_BRANCH"
          fi

          cp -r profiling/results "$RESULTS_DIR"

          git show "$GITHUB_SHA:profiling/generate_summary.py" | \
            PROFILE_SOURCE_SHA="$GITHUB_SHA" PROFILE_SOURCE_REF="$GITHUB_REF_NAME" python
          git add "$RESULTS_DIR" *.html
          git commit -m "Commit $SHA_COMMIT: automated report"
          git push origin "$PROFILING_BRANCH"
